### ISSUE TITLE
System.Threading.Tasks.Task.ThrowIfExceptional on Azure

### ISSUE THREAD

**Issue by JakubHolovsky** [fluentscheduler/FluentScheduler#223]
I am running FluentScheduler in my Web API on Azure. I have implemented the registry according to the recommended aproach in here.

My excecute function method looks like this:

 ```
public void Execute()
        {
            try
            {
                lock (_lock)
                {
                    if (_shuttingDown)
                        return;

                    var ctx = new OurCompanyEntities();
                    {
                        var appointmentRepository = new AppointmentRepository(ctx);
                        appointmentRepository.UpdateAppointmentViewingReportRequestedAsync().Wait();
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Log(ex);
            }
            finally
            {
                // Always unregister the job when done.
                HostingEnvironment.UnregisterObject(this);
            }
        }
```
The method gets triggered without any problems and it actually seems that it successfully finishes.
However in the error event I am getting following exception:

> Message: One or more errors occurred., StackTrace: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>  at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>  at MoovShack.ServerApi.Jobs.UpdateAppointmentsJob.Execute()

I actually tried rewriting UpdateAppointmentViewingReportRequestedAsync as sync so I wouldn't need to Wait() for it. However this didn't prevent the exception from happening.

As the Job finishes fine I am actually not too bothered by it but enough to raise an issue here as something seems off in there. Any suggestions welcomed.

**Comment by JakubHolovsky** [comment]
bug on our side - fluent scheduler works as expected
